"""add receipt print settings columns

Revision ID: 05e907d3e0cb
Revises: 6d694fcb64fd
Create Date: 2025-08-13 16:15:14.436992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e907d3e0cb'
down_revision = '6d694fcb64fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_paper_width', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('receipt_margin_top_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receipt_margin_bottom_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receipt_margin_left_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receipt_margin_right_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receipt_font_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receipt_show_logo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receipt_show_tax_number', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receipt_footer_text', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('receipt_footer_text')
        batch_op.drop_column('receipt_show_tax_number')
        batch_op.drop_column('receipt_show_logo')
        batch_op.drop_column('receipt_font_size')
        batch_op.drop_column('receipt_margin_right_mm')
        batch_op.drop_column('receipt_margin_left_mm')
        batch_op.drop_column('receipt_margin_bottom_mm')
        batch_op.drop_column('receipt_margin_top_mm')
        batch_op.drop_column('receipt_paper_width')

    # ### end Alembic commands ###
