"""add default_theme to settings

Revision ID: 24a825dc5561
Revises: 769a112b56f4
Create Date: 2025-08-12 01:29:06.125757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '24a825dc5561'
down_revision = '769a112b56f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists to avoid duplicates
    conn = op.get_bind()
    inspector = inspect(conn)

    try:
        columns = [c['name'] for c in inspector.get_columns('settings')]
        if 'default_theme' not in columns:
            with op.batch_alter_table('settings', schema=None) as batch_op:
                batch_op.add_column(sa.Column('default_theme', sa.String(length=10), nullable=True))
    except Exception:
        # If settings table doesn't exist, skip
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('default_theme')

    # ### end Alembic commands ###
