"""add minimal accounting layer

Revision ID: 544d7f83a73b
Revises: 9cdfd5fec1cc
Create Date: 2025-08-11 19:35:30.433621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544d7f83a73b'
down_revision = '9cdfd5fec1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entries')
    op.drop_table('accounts')
    # ### end Alembic commands ###
