"""add user_permissions table

Revision ID: 6d694fcb64fd
Revises: 24a825dc5561
Create Date: 2025-08-12 01:45:40.742827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d694fcb64fd'
down_revision = '24a825dc5561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('screen_key', sa.String(length=50), nullable=False),
    sa.Column('branch_scope', sa.String(length=20), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_add', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_print', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'screen_key', 'branch_scope', name='uq_user_screen_branch')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
