"""add settings model

Revision ID: 769a112b56f4
Revises: 544d7f83a73b
Create Date: 2025-08-11 20:25:55.487231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769a112b56f4'
down_revision = '544d7f83a73b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('place_india_label', sa.String(length=100), nullable=True),
    sa.Column('china_town_label', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
